MoM = int(input("how old is your mom?:"))
print(MoM + 20)
Dad = int(input("how old is your Dad?:"))
print(Dad + 20)
Sister = int(input("how old is your Sister?:"))
print(Sister + 20)
Brother = int(input("how old is your Brother?:"))
print(Brother + 20)
Uncle = int(input("how old is your Uncle?:"))
print(Uncle + 20)
grandfather = int(input("how old is your Grandfather?:"))
print(grandfather + 20)
Grandma = int(input("how old is your Grandma?:"))
print(Grandma + 20)